spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:h2:mem:order_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:data.sql
  zipkin:
    service:
      name: order-service
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000  

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.example.orderservice: DEBUG