spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:${CONFIG_SERVER}"
  datasource:
    url: jdbc:h2:mem:product_db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:data.sql
  zipkin:
    service:
      name: product-service
    base-url: ${ZIPKIN_SERVER}
    enabled: true
  sleuth:
    sampler:
      probability: 1

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.example.productservice: DEBUG